{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-cache",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-cache-1.0.0.jar",
          "url": "rsmod-cache-1.0.0.jar",
          "size": 194275,
          "sha512": "317330b54ba8a508fc88caf3f5dd2deb602b8263af63b15e2baf15e8278714e86d7d77ba31ba59ad16e2f296b919cc7ddcd12a99c954d76bdf38bcba71c51162",
          "sha256": "89e7f27af43be7c88c880f458057eafe3b703f1b3eadd7824f55094c54383a9f",
          "sha1": "0ee0078c3c0ccc68154cba59ba54175804d0f792",
          "md5": "719812e955920c828c5a1556ddd368fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.advo",
          "module": "rsmod-map",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.advo",
          "module": "rsmod-types",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.87.Final"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-buffer",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-cache",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-cache-1.0.0.jar",
          "url": "rsmod-cache-1.0.0.jar",
          "size": 194275,
          "sha512": "317330b54ba8a508fc88caf3f5dd2deb602b8263af63b15e2baf15e8278714e86d7d77ba31ba59ad16e2f296b919cc7ddcd12a99c954d76bdf38bcba71c51162",
          "sha256": "89e7f27af43be7c88c880f458057eafe3b703f1b3eadd7824f55094c54383a9f",
          "sha1": "0ee0078c3c0ccc68154cba59ba54175804d0f792",
          "md5": "719812e955920c828c5a1556ddd368fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-cache-1.0.0-javadoc.jar",
          "url": "rsmod-cache-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "08b759b5f93813b08a9336bfd5d09bbd3c7514bb150c07575737190dad5d531e7e02224d878680c3caec0c62ab28640ae8935233c9b9ef2e80f8d59c99174d83",
          "sha256": "3633bec8349e272ecf20b09ae4f321b2d93c00490d0a07e801bf343a00ecbd90",
          "sha1": "01ae6e51d749c9a00521b788755f8139bb7fd7ee",
          "md5": "ae31403e0cc5a2725ee3eb1d1f12983b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-cache-1.0.0-sources.jar",
          "url": "rsmod-cache-1.0.0-sources.jar",
          "size": 44461,
          "sha512": "01d9aa8c4e3b6f5070f7016f355aa677626101451a135c85b70cf780afa2c80425a41a4a5834e5cf409296f527acb69c37113c260e270b7f5b09405cc850b5e6",
          "sha256": "d571c2f0eabdf8a8267f9ff90d49af5808826800ecf1733258c7628254100ba4",
          "sha1": "150b2b80a3fe6486b3de5b00e9586112b8432bd6",
          "md5": "8f676a36e7807a7e1789cb989378f04c"
        },
        {
          "name": "rsmod-cache-1.0.0-sources.jar",
          "url": "rsmod-cache-1.0.0-sources.jar",
          "size": 44461,
          "sha512": "01d9aa8c4e3b6f5070f7016f355aa677626101451a135c85b70cf780afa2c80425a41a4a5834e5cf409296f527acb69c37113c260e270b7f5b09405cc850b5e6",
          "sha256": "d571c2f0eabdf8a8267f9ff90d49af5808826800ecf1733258c7628254100ba4",
          "sha1": "150b2b80a3fe6486b3de5b00e9586112b8432bd6",
          "md5": "8f676a36e7807a7e1789cb989378f04c"
        }
      ]
    }
  ]
}
