{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-map",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-map-1.0.0.jar",
          "url": "rsmod-map-1.0.0.jar",
          "size": 50384,
          "sha512": "48f22a3f79dd4997dc0d7e1e24f742f722c948e25c7aa9085c63b811dca564810a662648b33416bde6089eb844566ec855291c1f07e4f0914152473e50c7a4a9",
          "sha256": "094ea07311ff9f3959d0d027a72705083bd132e3b87e52c2e104800032c748ff",
          "sha1": "1b578d754a09b5c9810ad1fb5373b98274761f03",
          "md5": "16c534ecdc1d83b55b4956f62c0add81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-map-1.0.0.jar",
          "url": "rsmod-map-1.0.0.jar",
          "size": 50384,
          "sha512": "48f22a3f79dd4997dc0d7e1e24f742f722c948e25c7aa9085c63b811dca564810a662648b33416bde6089eb844566ec855291c1f07e4f0914152473e50c7a4a9",
          "sha256": "094ea07311ff9f3959d0d027a72705083bd132e3b87e52c2e104800032c748ff",
          "sha1": "1b578d754a09b5c9810ad1fb5373b98274761f03",
          "md5": "16c534ecdc1d83b55b4956f62c0add81"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-map-1.0.0-javadoc.jar",
          "url": "rsmod-map-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "bc21c9c278afe570f506961a58039355a87fa8f85c81562f6c2afee3cfe37359831570c619fe47025fb807a927c12f16fc09ec0987f3b30ba60c7827b215a0c2",
          "sha256": "bf605fae90ef39a981fc9f8d3eba97e237fbff542e185be9492a4603ec9f6a30",
          "sha1": "4adaac4ce89d9bd44dba4134d6a3c54916887b9e",
          "md5": "4a31804a455b3401f77146c5ce07a18e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-map-1.0.0-sources.jar",
          "url": "rsmod-map-1.0.0-sources.jar",
          "size": 11534,
          "sha512": "44005293eef128164a6ce11197025da24c19e2b241c41122e22eef17abbe0ddc2a7e0a8a4ba16951347ed5d4a8f1b0cc92c625545d286c2902f87895c6fd8ef6",
          "sha256": "ce98f2d1e3fab9192fa483d0960a765aa00d22a666d05da9b2f4e3df0e29bff9",
          "sha1": "8bdf8e66fcdd45f2d548389cc5b5a1302ef42994",
          "md5": "9247da811c0a5d0f2f0a6d2501880614"
        },
        {
          "name": "rsmod-map-1.0.0-sources.jar",
          "url": "rsmod-map-1.0.0-sources.jar",
          "size": 11534,
          "sha512": "44005293eef128164a6ce11197025da24c19e2b241c41122e22eef17abbe0ddc2a7e0a8a4ba16951347ed5d4a8f1b0cc92c625545d286c2902f87895c6fd8ef6",
          "sha256": "ce98f2d1e3fab9192fa483d0960a765aa00d22a666d05da9b2f4e3df0e29bff9",
          "sha1": "8bdf8e66fcdd45f2d548389cc5b5a1302ef42994",
          "md5": "9247da811c0a5d0f2f0a6d2501880614"
        }
      ]
    }
  ]
}
