{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-map",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-map-1.0.0.jar",
          "url": "rsmod-map-1.0.0.jar",
          "size": 49867,
          "sha512": "43ce513951db97ba648b77e0c512dac71b2764b26ac4d887a1dd07c3c878592dc3b6b5b93d65782b2b24dc64ffe7d2030bf1d846ec4a902b2c92a51051f34b07",
          "sha256": "44a99349e295a30327403053e48e41c0df91554ee077a8ea6a4b792e72ba7f0f",
          "sha1": "854e9bbea3976011c9b44d7315ada420e2dad246",
          "md5": "cb75a2fa5b88579f917f8d7959e6538a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-map-1.0.0.jar",
          "url": "rsmod-map-1.0.0.jar",
          "size": 49867,
          "sha512": "43ce513951db97ba648b77e0c512dac71b2764b26ac4d887a1dd07c3c878592dc3b6b5b93d65782b2b24dc64ffe7d2030bf1d846ec4a902b2c92a51051f34b07",
          "sha256": "44a99349e295a30327403053e48e41c0df91554ee077a8ea6a4b792e72ba7f0f",
          "sha1": "854e9bbea3976011c9b44d7315ada420e2dad246",
          "md5": "cb75a2fa5b88579f917f8d7959e6538a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-map-1.0.0-javadoc.jar",
          "url": "rsmod-map-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "bc21c9c278afe570f506961a58039355a87fa8f85c81562f6c2afee3cfe37359831570c619fe47025fb807a927c12f16fc09ec0987f3b30ba60c7827b215a0c2",
          "sha256": "bf605fae90ef39a981fc9f8d3eba97e237fbff542e185be9492a4603ec9f6a30",
          "sha1": "4adaac4ce89d9bd44dba4134d6a3c54916887b9e",
          "md5": "4a31804a455b3401f77146c5ce07a18e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-map-1.0.0-sources.jar",
          "url": "rsmod-map-1.0.0-sources.jar",
          "size": 11534,
          "sha512": "aa02e2fb5d458a00afd18de55c1f9d3fac47f88be4f60ca21216255df1cdb33ae41f4c11335248b9639079fee4de43f6e45cc31244f15f016378d70a2553f660",
          "sha256": "d2880e64c4a753b59cbff61cc8229a02c205ec0a4b760720c29e1bb58a62242a",
          "sha1": "f99ee55064df02aea2b540b90bf0f9eeaa1ab7b9",
          "md5": "a8c697f6304e682c9cc1f1df69afc335"
        },
        {
          "name": "rsmod-map-1.0.0-sources.jar",
          "url": "rsmod-map-1.0.0-sources.jar",
          "size": 11534,
          "sha512": "aa02e2fb5d458a00afd18de55c1f9d3fac47f88be4f60ca21216255df1cdb33ae41f4c11335248b9639079fee4de43f6e45cc31244f15f016378d70a2553f660",
          "sha256": "d2880e64c4a753b59cbff61cc8229a02c205ec0a4b760720c29e1bb58a62242a",
          "sha1": "f99ee55064df02aea2b540b90bf0f9eeaa1ab7b9",
          "md5": "a8c697f6304e682c9cc1f1df69afc335"
        }
      ]
    }
  ]
}
