{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-events",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-events-1.0.0.jar",
          "url": "rsmod-events-1.0.0.jar",
          "size": 8407,
          "sha512": "89efa79c7c4d10939958085af7c68cc8fd6ded287ae7843adada21db82424cb0537b0f70c5b6270aeb404144c05c2ea42b7c478de0b8c389536520f9749ebea0",
          "sha256": "1d38b3e250118d6fdd6334c1c976266fb87af30384df9f206521a7720356c0f1",
          "sha1": "e1bd556a6c5c2799eacadf3c30668e46114cfaea",
          "md5": "0f6cb7859a3d421897baca6afc1cb5da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-events-1.0.0.jar",
          "url": "rsmod-events-1.0.0.jar",
          "size": 8407,
          "sha512": "89efa79c7c4d10939958085af7c68cc8fd6ded287ae7843adada21db82424cb0537b0f70c5b6270aeb404144c05c2ea42b7c478de0b8c389536520f9749ebea0",
          "sha256": "1d38b3e250118d6fdd6334c1c976266fb87af30384df9f206521a7720356c0f1",
          "sha1": "e1bd556a6c5c2799eacadf3c30668e46114cfaea",
          "md5": "0f6cb7859a3d421897baca6afc1cb5da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-events-1.0.0-javadoc.jar",
          "url": "rsmod-events-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "24f9fde27b42249779a0648b61fff3302869021fabac16a0798f9d8047d408bb4f35e0b9c85962d0f5a5dfa7bad8e0c394642e6f33df54d1e702f0deac6bac56",
          "sha256": "967baeffe135e6174d792996b0b59d9fc98ca0d236f93c08beeeb70d25993f38",
          "sha1": "522069435c30d88112314b6ed54793307407213e",
          "md5": "cd386280cd68c60cf128dede71fe3708"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-events-1.0.0-sources.jar",
          "url": "rsmod-events-1.0.0-sources.jar",
          "size": 1894,
          "sha512": "8eefe0fe06353aa94efc4ebaf1712035af9c4f489e762d1cc0c912440553aa76e8334ecc635f21bfaf5d1f23dfb6004941236a8a961c2203ef64953da61f052c",
          "sha256": "090224055cce43840b0938864fc7943c7a3076964b0f7f3702abb6cb04c9f582",
          "sha1": "8b5e4a9b17206376e771df7eaa621a5d54c6c433",
          "md5": "ecf3ee2cf735b632fca5fbbd3d7bb806"
        },
        {
          "name": "rsmod-events-1.0.0-sources.jar",
          "url": "rsmod-events-1.0.0-sources.jar",
          "size": 1894,
          "sha512": "8eefe0fe06353aa94efc4ebaf1712035af9c4f489e762d1cc0c912440553aa76e8334ecc635f21bfaf5d1f23dfb6004941236a8a961c2203ef64953da61f052c",
          "sha256": "090224055cce43840b0938864fc7943c7a3076964b0f7f3702abb6cb04c9f582",
          "sha1": "8b5e4a9b17206376e771df7eaa621a5d54c6c433",
          "md5": "ecf3ee2cf735b632fca5fbbd3d7bb806"
        }
      ]
    }
  ]
}
