{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-events",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-events-1.0.0.jar",
          "url": "rsmod-events-1.0.0.jar",
          "size": 8401,
          "sha512": "17fdb35c9af773d22c2ec454c9ff663f62d2f985796651ba101f5ea8c3559b852b01918b8f93ebe34100af240c0a30cef21c56460d40773fd051987aa6bc6238",
          "sha256": "bbacd35a84e6acf9030ce569d324952db785fb226e556c11b96ba05fb0bf7992",
          "sha1": "bac29e99a8fc102d8c6f60c987610eb0aa2d334b",
          "md5": "46feed1d6a2805070f35d9a19496ee6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-events-1.0.0.jar",
          "url": "rsmod-events-1.0.0.jar",
          "size": 8401,
          "sha512": "17fdb35c9af773d22c2ec454c9ff663f62d2f985796651ba101f5ea8c3559b852b01918b8f93ebe34100af240c0a30cef21c56460d40773fd051987aa6bc6238",
          "sha256": "bbacd35a84e6acf9030ce569d324952db785fb226e556c11b96ba05fb0bf7992",
          "sha1": "bac29e99a8fc102d8c6f60c987610eb0aa2d334b",
          "md5": "46feed1d6a2805070f35d9a19496ee6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-events-1.0.0-javadoc.jar",
          "url": "rsmod-events-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "24f9fde27b42249779a0648b61fff3302869021fabac16a0798f9d8047d408bb4f35e0b9c85962d0f5a5dfa7bad8e0c394642e6f33df54d1e702f0deac6bac56",
          "sha256": "967baeffe135e6174d792996b0b59d9fc98ca0d236f93c08beeeb70d25993f38",
          "sha1": "522069435c30d88112314b6ed54793307407213e",
          "md5": "cd386280cd68c60cf128dede71fe3708"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-events-1.0.0-sources.jar",
          "url": "rsmod-events-1.0.0-sources.jar",
          "size": 1894,
          "sha512": "04fa28d4803cef0c5a3c97169747632523c33bc3e8ddac82cea0b087242a446c9ff81d3f0a4b4d4dbf7c132794aaf31362b27f3b6e17704e82228344b0546a13",
          "sha256": "bbab1a79ee24c712c4b00284ed53ef4ed6bcc2646df3cd65d792a130c6933531",
          "sha1": "bd709c7ae6813a15b8ac19d7ec6336174e35e0e0",
          "md5": "5ffade10e8e2f8c1672d1d786d6f2ec0"
        },
        {
          "name": "rsmod-events-1.0.0-sources.jar",
          "url": "rsmod-events-1.0.0-sources.jar",
          "size": 1894,
          "sha512": "04fa28d4803cef0c5a3c97169747632523c33bc3e8ddac82cea0b087242a446c9ff81d3f0a4b4d4dbf7c132794aaf31362b27f3b6e17704e82228344b0546a13",
          "sha256": "bbab1a79ee24c712c4b00284ed53ef4ed6bcc2646df3cd65d792a130c6933531",
          "sha1": "bd709c7ae6813a15b8ac19d7ec6336174e35e0e0",
          "md5": "5ffade10e8e2f8c1672d1d786d6f2ec0"
        }
      ]
    }
  ]
}
