{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rsprot",
    "module": "osrs-221-internal",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-221-internal-1.0-SNAPSHOT.jar",
          "url": "osrs-221-internal-1.0-SNAPSHOT.jar",
          "size": 105680,
          "sha512": "e1777cae98072371f248b5d6578ecc9e0983ef2eea9118ca8d644d2ce6faa91c74c25dd25c8b1477ed1d6002dfa987debd6343f8d2d11d3a9f981f17eabdebcc",
          "sha256": "b780c648009a61b2d183614490d5aa1950ce52e198d56e949653dce2b51be5b9",
          "sha1": "405ac25710031f10d832d73d125a14e9baa007c7",
          "md5": "28695a635a8786223f31487aebdc6c4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-bom",
          "version": {
            "requires": "4.1.109.Final"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "io.netty",
          "module": "netty-transport"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-pool2",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.rsprot",
          "module": "buffer",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "compression",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "protocol",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-221-internal-1.0-SNAPSHOT.jar",
          "url": "osrs-221-internal-1.0-SNAPSHOT.jar",
          "size": 105680,
          "sha512": "e1777cae98072371f248b5d6578ecc9e0983ef2eea9118ca8d644d2ce6faa91c74c25dd25c8b1477ed1d6002dfa987debd6343f8d2d11d3a9f981f17eabdebcc",
          "sha256": "b780c648009a61b2d183614490d5aa1950ce52e198d56e949653dce2b51be5b9",
          "sha1": "405ac25710031f10d832d73d125a14e9baa007c7",
          "md5": "28695a635a8786223f31487aebdc6c4a"
        }
      ]
    }
  ]
}
