{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-toml",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-toml-1.0.0.jar",
          "url": "rsmod-toml-1.0.0.jar",
          "size": 3596,
          "sha512": "49a28d3da8b588cf62549f8d0614e5107296f2ce1b7dd0dcd06a32bcbe9eb56d915a774f73c45aa279ccced2044235ece3eee7b3688efb728a83b86ba6f028b1",
          "sha256": "6864ec296dd02c707a3505e073b603a82af2eb2697bd91a34bc6f2c3b7e7e4ea",
          "sha1": "d304db872e51acd3f6ceb4bbf62841e37d49d725",
          "md5": "b1919b69ba66305da05fb276ba54daa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-toml",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-toml-1.0.0.jar",
          "url": "rsmod-toml-1.0.0.jar",
          "size": 3596,
          "sha512": "49a28d3da8b588cf62549f8d0614e5107296f2ce1b7dd0dcd06a32bcbe9eb56d915a774f73c45aa279ccced2044235ece3eee7b3688efb728a83b86ba6f028b1",
          "sha256": "6864ec296dd02c707a3505e073b603a82af2eb2697bd91a34bc6f2c3b7e7e4ea",
          "sha1": "d304db872e51acd3f6ceb4bbf62841e37d49d725",
          "md5": "b1919b69ba66305da05fb276ba54daa4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-toml-1.0.0-javadoc.jar",
          "url": "rsmod-toml-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "cbf29587f9dd641bcb1778a01f7d9ec248b1e5fc0bbc03f2bf09552d7e549f61319395a7dc7ae0c39a3e7201a59b33f2f882d53643585ac27684160cd69502d4",
          "sha256": "3877756a5047a6cce3b39dfc03272c56b399782d71b51ac899fd521b4dc530c4",
          "sha1": "e958affc04c0e260eb472c96560f7f47570b7fb9",
          "md5": "30aa8af0585ad019f32ee3c4d9679f36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-toml-1.0.0-sources.jar",
          "url": "rsmod-toml-1.0.0-sources.jar",
          "size": 1700,
          "sha512": "2b3c8df99bc9937241fdf06ef36d43984f6b41a0f384cb17bb015251e21aa5742db1da3d9e672b71d09f86a5464ea8d911db203091fcb3a92c753e57f3e3d2a4",
          "sha256": "7aed4345cf9b85f4a3d685ef8bfa8a577564f73af61ecc947a220042e6206352",
          "sha1": "e17c5094a4e47bf3d8ecd7a5d7b5aaa812c509d8",
          "md5": "e3d409a977ad77db8f48e194f8227841"
        },
        {
          "name": "rsmod-toml-1.0.0-sources.jar",
          "url": "rsmod-toml-1.0.0-sources.jar",
          "size": 1700,
          "sha512": "2b3c8df99bc9937241fdf06ef36d43984f6b41a0f384cb17bb015251e21aa5742db1da3d9e672b71d09f86a5464ea8d911db203091fcb3a92c753e57f3e3d2a4",
          "sha256": "7aed4345cf9b85f4a3d685ef8bfa8a577564f73af61ecc947a220042e6206352",
          "sha1": "e17c5094a4e47bf3d8ecd7a5d7b5aaa812c509d8",
          "md5": "e3d409a977ad77db8f48e194f8227841"
        }
      ]
    }
  ]
}
