{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-toml",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-toml-1.0.0.jar",
          "url": "rsmod-toml-1.0.0.jar",
          "size": 3605,
          "sha512": "9cedbb513c4926d82ff30d299d3258b9d20e9ced3627bf597ac96038b913ab1317ca4e0fa73c9393d6e79d8fd2611f0dc096cf3bd4b0dd1e8d1c241dd66deb11",
          "sha256": "68324f37d693829384fdce412efeacecf8c0c17cee050d785c6536de5bec627c",
          "sha1": "fbe971b7e8433cbaeaf789b9ada763f8abc5af36",
          "md5": "d5570f796b7ae2430cb356c6e79cc9ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-toml",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-toml-1.0.0.jar",
          "url": "rsmod-toml-1.0.0.jar",
          "size": 3605,
          "sha512": "9cedbb513c4926d82ff30d299d3258b9d20e9ced3627bf597ac96038b913ab1317ca4e0fa73c9393d6e79d8fd2611f0dc096cf3bd4b0dd1e8d1c241dd66deb11",
          "sha256": "68324f37d693829384fdce412efeacecf8c0c17cee050d785c6536de5bec627c",
          "sha1": "fbe971b7e8433cbaeaf789b9ada763f8abc5af36",
          "md5": "d5570f796b7ae2430cb356c6e79cc9ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-toml-1.0.0-javadoc.jar",
          "url": "rsmod-toml-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "cbf29587f9dd641bcb1778a01f7d9ec248b1e5fc0bbc03f2bf09552d7e549f61319395a7dc7ae0c39a3e7201a59b33f2f882d53643585ac27684160cd69502d4",
          "sha256": "3877756a5047a6cce3b39dfc03272c56b399782d71b51ac899fd521b4dc530c4",
          "sha1": "e958affc04c0e260eb472c96560f7f47570b7fb9",
          "md5": "30aa8af0585ad019f32ee3c4d9679f36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-toml-1.0.0-sources.jar",
          "url": "rsmod-toml-1.0.0-sources.jar",
          "size": 1700,
          "sha512": "6a2b36fa2708d2c776afc34279c929ec8bdaeb030ed57a8508ec6df1a846755d7a799b345f314b1f583b61d38d3a3e902718021eae4a2452767c833fe0f37618",
          "sha256": "e48a2dd72d3ac2897b81108e96af5168d7bddfb35b2d8a9ed2f371d2e652508b",
          "sha1": "fd03d170877b7196459847b18879be4944b4641a",
          "md5": "db4b59714bf89fbe176f48a663b5f947"
        },
        {
          "name": "rsmod-toml-1.0.0-sources.jar",
          "url": "rsmod-toml-1.0.0-sources.jar",
          "size": 1700,
          "sha512": "6a2b36fa2708d2c776afc34279c929ec8bdaeb030ed57a8508ec6df1a846755d7a799b345f314b1f583b61d38d3a3e902718021eae4a2452767c833fe0f37618",
          "sha256": "e48a2dd72d3ac2897b81108e96af5168d7bddfb35b2d8a9ed2f371d2e652508b",
          "sha1": "fd03d170877b7196459847b18879be4944b4641a",
          "md5": "db4b59714bf89fbe176f48a663b5f947"
        }
      ]
    }
  ]
}
