{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-buffer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-buffer-1.0.0.jar",
          "url": "rsmod-buffer-1.0.0.jar",
          "size": 1538,
          "sha512": "c615e0c95882342081ba372ad72d0ff34ece95621505018910d6e4a265320cdeb7a158f7b7ccf3eb8b77740c103d0b3147be022c3b52054982e60073933e7d0e",
          "sha256": "0468db15b2efe718f661b413ff1ed35dec7f0574bd139117bf1f471749e9b35c",
          "sha1": "a71a3b7d1545d73dba25971bb8f6bac88a0e4094",
          "md5": "26ca6b4228548bf50bbefc36698620a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.87.Final"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-buffer-1.0.0.jar",
          "url": "rsmod-buffer-1.0.0.jar",
          "size": 1538,
          "sha512": "c615e0c95882342081ba372ad72d0ff34ece95621505018910d6e4a265320cdeb7a158f7b7ccf3eb8b77740c103d0b3147be022c3b52054982e60073933e7d0e",
          "sha256": "0468db15b2efe718f661b413ff1ed35dec7f0574bd139117bf1f471749e9b35c",
          "sha1": "a71a3b7d1545d73dba25971bb8f6bac88a0e4094",
          "md5": "26ca6b4228548bf50bbefc36698620a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-buffer-1.0.0-javadoc.jar",
          "url": "rsmod-buffer-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "aa2c258c6bfc7360dd17c8af058e856785aeb0484b222c1b6de49c450736dff57b06100419be25d878d84c2600902185851ffd47f3291e78eb49b4731cdfa08c",
          "sha256": "488482302837c9ae8701032d42972ddc430c5d9688ed5ad44b80956b52c04743",
          "sha1": "06def39eaa11cec17f065bb80b01d3d5508ad099",
          "md5": "565521d3919b6005c54b9e9c3b4fd06f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-buffer-1.0.0-sources.jar",
          "url": "rsmod-buffer-1.0.0-sources.jar",
          "size": 891,
          "sha512": "54a2b2025bbf298064967a785af10bb63953e4b7e14282d83506ba5dbf87bfb69928558576c00824fc3a09287b0b2e4582ed043d31304cf7bdc515fac8f209f0",
          "sha256": "c6e897fe07513640147ef349deebcd86c72375b62cf726b4ed802dcc3da42ee0",
          "sha1": "639ca0a1fe54766e495a839a092b5bbb401ed66b",
          "md5": "6381950661e6f7f1baba13039afd42d8"
        },
        {
          "name": "rsmod-buffer-1.0.0-sources.jar",
          "url": "rsmod-buffer-1.0.0-sources.jar",
          "size": 891,
          "sha512": "54a2b2025bbf298064967a785af10bb63953e4b7e14282d83506ba5dbf87bfb69928558576c00824fc3a09287b0b2e4582ed043d31304cf7bdc515fac8f209f0",
          "sha256": "c6e897fe07513640147ef349deebcd86c72375b62cf726b4ed802dcc3da42ee0",
          "sha1": "639ca0a1fe54766e495a839a092b5bbb401ed66b",
          "md5": "6381950661e6f7f1baba13039afd42d8"
        }
      ]
    }
  ]
}
