{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rsprot",
    "module": "osrs-221-desktop",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-221-desktop-1.0-SNAPSHOT.jar",
          "url": "osrs-221-desktop-1.0-SNAPSHOT.jar",
          "size": 501798,
          "sha512": "1f0c92dc154ad901005dbcffdfa3817586653c68f486b715c517331b0f3c5311ae5e16361eff3c3af852c759d2c510dbeb9687a2a29737c3a9df26f6e9f26cc6",
          "sha256": "a481a8507266b881835147aea43fc2c368775cf0333c6d547225161c3584b85f",
          "sha1": "ddb5c388be2df740e1d1705c9a8ee54404b4a45b",
          "md5": "8d01aa56b696a521ac22b9b60525b1b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-bom",
          "version": {
            "requires": "4.1.109.Final"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "io.netty",
          "module": "netty-transport"
        },
        {
          "group": "net.rsprot",
          "module": "buffer",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "compression",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "crypto",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "protocol",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-model",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-internal",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-221-desktop-1.0-SNAPSHOT.jar",
          "url": "osrs-221-desktop-1.0-SNAPSHOT.jar",
          "size": 501798,
          "sha512": "1f0c92dc154ad901005dbcffdfa3817586653c68f486b715c517331b0f3c5311ae5e16361eff3c3af852c759d2c510dbeb9687a2a29737c3a9df26f6e9f26cc6",
          "sha256": "a481a8507266b881835147aea43fc2c368775cf0333c6d547225161c3584b85f",
          "sha1": "ddb5c388be2df740e1d1705c9a8ee54404b4a45b",
          "md5": "8d01aa56b696a521ac22b9b60525b1b9"
        }
      ]
    }
  ]
}
