{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-coroutines",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-coroutines-2.1.0.jar",
          "url": "rsmod-coroutines-2.1.0.jar",
          "size": 16959,
          "sha512": "515a932445f8e69da2f82582a52e16e487084b7dfd17780d5b4a1644866e724e2cddcb54bf0416a1342570ff96475cb6d9b98cbab5f5f3770cdaa2da1106841f",
          "sha256": "fd911dd0eb98a77cbdd6509d9a3331606380862c70fd5731c3f08451ad1376a9",
          "sha1": "ade0163d99da49a510f1990440b0034be3999448",
          "md5": "9293dc7e4fefb0e24fd1b48752d30b4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-coroutines-2.1.0.jar",
          "url": "rsmod-coroutines-2.1.0.jar",
          "size": 16959,
          "sha512": "515a932445f8e69da2f82582a52e16e487084b7dfd17780d5b4a1644866e724e2cddcb54bf0416a1342570ff96475cb6d9b98cbab5f5f3770cdaa2da1106841f",
          "sha256": "fd911dd0eb98a77cbdd6509d9a3331606380862c70fd5731c3f08451ad1376a9",
          "sha1": "ade0163d99da49a510f1990440b0034be3999448",
          "md5": "9293dc7e4fefb0e24fd1b48752d30b4f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-coroutines-2.1.0-javadoc.jar",
          "url": "rsmod-coroutines-2.1.0-javadoc.jar",
          "size": 261,
          "sha512": "4e4b7bbe2f3f88fec191844248124bdf03397d400d21673bb1b63a00e477af0568a1cafefd110a1488ff8df55bb3971cc375c0a90f541014493ed50e21cf6c5a",
          "sha256": "97e7dea4951c8cbcb58e47ca6f1b05683b9c2a79a32d9016fbf26226afe8c9f8",
          "sha1": "c0c630417e856294da07fd8b880c8953000fca68",
          "md5": "9d500472f52eb6db7024dedd04b640ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-coroutines-2.1.0-sources.jar",
          "url": "rsmod-coroutines-2.1.0-sources.jar",
          "size": 5147,
          "sha512": "17f93b130616b178dc21f481ff91387fbed4974898eaa5a537615aed08bac52e8e21de3da39335aa5e7b35d9a4cde3939d0bc6379ec2ebe9a3715fec481b6ef5",
          "sha256": "2eef971ca4b5c0b60f65adbe3d923a215cfcd604d534366e6c14f35b307dc37d",
          "sha1": "8aff372fa80dd011426fb87b1fec1ee58505510e",
          "md5": "79d8539b1e7ca866bbe013d924d15a87"
        },
        {
          "name": "rsmod-coroutines-2.1.0-sources.jar",
          "url": "rsmod-coroutines-2.1.0-sources.jar",
          "size": 5147,
          "sha512": "17f93b130616b178dc21f481ff91387fbed4974898eaa5a537615aed08bac52e8e21de3da39335aa5e7b35d9a4cde3939d0bc6379ec2ebe9a3715fec481b6ef5",
          "sha256": "2eef971ca4b5c0b60f65adbe3d923a215cfcd604d534366e6c14f35b307dc37d",
          "sha1": "8aff372fa80dd011426fb87b1fec1ee58505510e",
          "md5": "79d8539b1e7ca866bbe013d924d15a87"
        }
      ]
    }
  ]
}
