{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "runelite-asm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-asm-1.0.0.jar",
          "url": "runelite-asm-1.0.0.jar",
          "size": 330150,
          "sha512": "7c5ef6ac2289f2ea8c98edd07cfec7658b83b5de3cdc77a0b333ba63a01eeeaf782f785e7c5352fcbb2aa7c43c3e125a2939edd417d0540c464d6abb2511fd30",
          "sha256": "fd71785367c1d86c7306be31b61c82ca0d71b26831a70ba463c04b042742706f",
          "sha1": "ecf5502bed24d32292906946330179e0b31e970e",
          "md5": "06c1db6e95a7005879ab924e69aad7dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-asm-1.0.0.jar",
          "url": "runelite-asm-1.0.0.jar",
          "size": 330150,
          "sha512": "7c5ef6ac2289f2ea8c98edd07cfec7658b83b5de3cdc77a0b333ba63a01eeeaf782f785e7c5352fcbb2aa7c43c3e125a2939edd417d0540c464d6abb2511fd30",
          "sha256": "fd71785367c1d86c7306be31b61c82ca0d71b26831a70ba463c04b042742706f",
          "sha1": "ecf5502bed24d32292906946330179e0b31e970e",
          "md5": "06c1db6e95a7005879ab924e69aad7dc"
        }
      ]
    }
  ]
}
