{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rsprot",
    "module": "osrs-221-shared",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-221-shared-1.0-SNAPSHOT.jar",
          "url": "osrs-221-shared-1.0-SNAPSHOT.jar",
          "size": 70977,
          "sha512": "92e0d46d16bf72757244d20f97baa0be143503f45d495dc46e28f6ebbfe78aef9700bd2c25a8fb5b729ebd48a882db860c6fe2795875275449227b3b8538a478",
          "sha256": "c942982b0750f4042fbfce6157a4d36e1d44268ae37c28e9a1c1ba37d284034d",
          "sha1": "bdb6db1562d17da90b0879cb22d72d6fae037b76",
          "md5": "2c1fb5273e4897b44987e39b0fa8ef90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-bom",
          "version": {
            "requires": "4.1.107.Final"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "io.netty",
          "module": "netty-transport"
        },
        {
          "group": "net.rsprot",
          "module": "buffer",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "compression",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "crypto",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "protocol",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-model",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-internal",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-221-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-221-shared-1.0-SNAPSHOT.jar",
          "url": "osrs-221-shared-1.0-SNAPSHOT.jar",
          "size": 70977,
          "sha512": "92e0d46d16bf72757244d20f97baa0be143503f45d495dc46e28f6ebbfe78aef9700bd2c25a8fb5b729ebd48a882db860c6fe2795875275449227b3b8538a478",
          "sha256": "c942982b0750f4042fbfce6157a4d36e1d44268ae37c28e9a1c1ba37d284034d",
          "sha1": "bdb6db1562d17da90b0879cb22d72d6fae037b76",
          "md5": "2c1fb5273e4897b44987e39b0fa8ef90"
        }
      ]
    }
  ]
}
