{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-info",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-info-1.0.1.jar",
          "url": "rsmod-info-1.0.1.jar",
          "size": 43383,
          "sha512": "91bae925b1c6b5c662aec691c0f5853682a12b8be479332c89ce4b560a2462d296d40654b2c099d5afd0542bcea4313c02fcf9186ebf119961359af5eb7e753c",
          "sha256": "3bdc4e1c145faad6a2461de72c0024b50aadae4f8aeb2b5a43a1a4256ff28818",
          "sha1": "2db16b67e1fbaee933ee83a1175bb67dd655bbad",
          "md5": "b6ac820a78d5940510fe1e569ec68793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-info-1.0.1.jar",
          "url": "rsmod-info-1.0.1.jar",
          "size": 43383,
          "sha512": "91bae925b1c6b5c662aec691c0f5853682a12b8be479332c89ce4b560a2462d296d40654b2c099d5afd0542bcea4313c02fcf9186ebf119961359af5eb7e753c",
          "sha256": "3bdc4e1c145faad6a2461de72c0024b50aadae4f8aeb2b5a43a1a4256ff28818",
          "sha1": "2db16b67e1fbaee933ee83a1175bb67dd655bbad",
          "md5": "b6ac820a78d5940510fe1e569ec68793"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-info-1.0.1-javadoc.jar",
          "url": "rsmod-info-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "b25c4edd16afbe68c13a7d1397e41e01c9c78ac0f2c5af6f05f8ab8b5c8c23383da6fd70290dbacb383ae982639e642595c2a2670d518450b0cb886770fa4fed",
          "sha256": "ae8b3540c01c44c3511196526668806dcc45d59de4799d9bfb34cb2c0846ccf1",
          "sha1": "c801b8f0a1adc1fd79ab6942c170399f66c6130b",
          "md5": "0894565dc44871307e799b5d340399b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-info-1.0.1-sources.jar",
          "url": "rsmod-info-1.0.1-sources.jar",
          "size": 12919,
          "sha512": "7d73b03eae0b06dbc20bc0c04d39e141c90d853cdca644d0f87f18bad3a0654baaf3454198c02b624e35754e03c896b15c3464ec7f3763534bcdba3d44ff2b87",
          "sha256": "00baf37f1dc5126139b48196ac922d4aaddedc383e92cfebb9230ece8c69d2f6",
          "sha1": "288d6217c3691c82cdfd875848a8f29c4e96fc95",
          "md5": "c8a594b6aeea1373671b301df184dc09"
        },
        {
          "name": "rsmod-info-1.0.1-sources.jar",
          "url": "rsmod-info-1.0.1-sources.jar",
          "size": 12919,
          "sha512": "7d73b03eae0b06dbc20bc0c04d39e141c90d853cdca644d0f87f18bad3a0654baaf3454198c02b624e35754e03c896b15c3464ec7f3763534bcdba3d44ff2b87",
          "sha256": "00baf37f1dc5126139b48196ac922d4aaddedc383e92cfebb9230ece8c69d2f6",
          "sha1": "288d6217c3691c82cdfd875848a8f29c4e96fc95",
          "md5": "c8a594b6aeea1373671b301df184dc09"
        }
      ]
    }
  ]
}
