{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-protocol",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-protocol-1.0.0.jar",
          "url": "rsmod-protocol-1.0.0.jar",
          "size": 21904,
          "sha512": "1d988e745bd8d0a2bd69627ad1028f349af4f214c452bf4c91700564b85c08330890dc293ed0569d20eda18a2eabaa1e0f2237ce45b9f6e2c045ff8412012244",
          "sha256": "a72a6cca0e931f77e6d499cab0fb7166cba700d2e59081d96c7fe02a191197a9",
          "sha1": "940542140394a985af839320512c40d55527b275",
          "md5": "9982448262aea6f499dd984f4c51e066"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.87.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.87.Final"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-crypto",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-protocol-1.0.0.jar",
          "url": "rsmod-protocol-1.0.0.jar",
          "size": 21904,
          "sha512": "1d988e745bd8d0a2bd69627ad1028f349af4f214c452bf4c91700564b85c08330890dc293ed0569d20eda18a2eabaa1e0f2237ce45b9f6e2c045ff8412012244",
          "sha256": "a72a6cca0e931f77e6d499cab0fb7166cba700d2e59081d96c7fe02a191197a9",
          "sha1": "940542140394a985af839320512c40d55527b275",
          "md5": "9982448262aea6f499dd984f4c51e066"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-protocol-1.0.0-javadoc.jar",
          "url": "rsmod-protocol-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "0e91b03a14119f3d2841bac3e32555ded136b0a092d7f08ba9cfb12766bc782e4cbee92f3077bdf1667f41b30b014fb4efd1938d2fdd4c2e3d4a492f0229aeaa",
          "sha256": "1e8a2ad73986d7ea3c33fd7d311b4137d7e1f58f64e9246710905b8e4f6a4078",
          "sha1": "7165dc48c7acbb3f6e05d7c159814f14a7ab933d",
          "md5": "5d1e5ddd76c4a47e09b533823fe5a411"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-protocol-1.0.0-sources.jar",
          "url": "rsmod-protocol-1.0.0-sources.jar",
          "size": 6501,
          "sha512": "4753d6be042137518574df3dbef988742390ac3e9498ec56787a459919f078c9f5d651294bc26b1c54026a6bdf56d1b340fffc10e74071e21fb2c348dd294101",
          "sha256": "0ff5e3d1cbd5b16829d6525eb5b5d6b87512b02ed65e4ee43b048b084cb081cf",
          "sha1": "cda810606673ff7e51165b5fd91b6199f0fe7956",
          "md5": "6b22e6880d2c54fb23b3e32eed330095"
        },
        {
          "name": "rsmod-protocol-1.0.0-sources.jar",
          "url": "rsmod-protocol-1.0.0-sources.jar",
          "size": 6501,
          "sha512": "4753d6be042137518574df3dbef988742390ac3e9498ec56787a459919f078c9f5d651294bc26b1c54026a6bdf56d1b340fffc10e74071e21fb2c348dd294101",
          "sha256": "0ff5e3d1cbd5b16829d6525eb5b5d6b87512b02ed65e4ee43b048b084cb081cf",
          "sha1": "cda810606673ff7e51165b5fd91b6199f0fe7956",
          "md5": "6b22e6880d2c54fb23b3e32eed330095"
        }
      ]
    }
  ]
}
