{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "poser-api",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "poser-api-1.3.4.jar",
          "url": "poser-api-1.3.4.jar",
          "size": 25703,
          "sha512": "7954ecb9824cef433f209e37a2d129f8536cf07f879441b6e53e18d8439b875d57a75f65638df28dbd30e512c867325dcd01378d49da24c6dab4cbe469dcfb99",
          "sha256": "36f4e94060c65320604c24890e1b00fdb4b149429b7ccbfc288fde41ecddef4e",
          "sha1": "ed2d4a93f24ce67895723e75ec4a043fab2636e9",
          "md5": "2397bb75d6ebd24d0c49c78476f52fbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.9.18"
          }
        }
      ],
      "files": [
        {
          "name": "poser-api-1.3.4.jar",
          "url": "poser-api-1.3.4.jar",
          "size": 25703,
          "sha512": "7954ecb9824cef433f209e37a2d129f8536cf07f879441b6e53e18d8439b875d57a75f65638df28dbd30e512c867325dcd01378d49da24c6dab4cbe469dcfb99",
          "sha256": "36f4e94060c65320604c24890e1b00fdb4b149429b7ccbfc288fde41ecddef4e",
          "sha1": "ed2d4a93f24ce67895723e75ec4a043fab2636e9",
          "md5": "2397bb75d6ebd24d0c49c78476f52fbc"
        }
      ]
    }
  ]
}
