{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "js5server",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.2.jar",
          "url": "js5server-1.0.2.jar",
          "size": 56782,
          "sha512": "d96720d7201b65b016fb25f9bc8630be0cc701a6061ded189f11d5a1eb8c7bb8ddd9ab97571dac6f21d6ec098f0b8251e63303d0009e49cb3924388aecc444cc",
          "sha256": "3a06a5c2b566ce531ac01ce1ede15fbea57547d72c503a462608e299ffd40c8a",
          "sha1": "3a292680cc59295bf016eeb937bac895ac7fba42",
          "md5": "9beb17487d647a5a0392a3b54acb5a35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          }
        },
        {
          "group": "org.jctools",
          "module": "jctools-core",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.2.jar",
          "url": "js5server-1.0.2.jar",
          "size": 56782,
          "sha512": "d96720d7201b65b016fb25f9bc8630be0cc701a6061ded189f11d5a1eb8c7bb8ddd9ab97571dac6f21d6ec098f0b8251e63303d0009e49cb3924388aecc444cc",
          "sha256": "3a06a5c2b566ce531ac01ce1ede15fbea57547d72c503a462608e299ffd40c8a",
          "sha1": "3a292680cc59295bf016eeb937bac895ac7fba42",
          "md5": "9beb17487d647a5a0392a3b54acb5a35"
        }
      ]
    }
  ]
}
