{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-types",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-types-1.0.0.jar",
          "url": "rsmod-types-1.0.0.jar",
          "size": 29947,
          "sha512": "4a278858179d76dd791989c5805a9f3120c18545a5ddd863dbc0336aceec3fab87448373d8fb4762eed3bd9b2a87af60e4339dae1eb938d3480143fc37f23836",
          "sha256": "034753ef8a7c7ee8b9b4f6ab04e8bd0314851f96079754fb1bda99620adf090f",
          "sha1": "a76a928e51c4df1ca0889e76b1b5612b9028ab4d",
          "md5": "acbcc8389f99831c745e1da792c4d6db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-types-1.0.0.jar",
          "url": "rsmod-types-1.0.0.jar",
          "size": 29947,
          "sha512": "4a278858179d76dd791989c5805a9f3120c18545a5ddd863dbc0336aceec3fab87448373d8fb4762eed3bd9b2a87af60e4339dae1eb938d3480143fc37f23836",
          "sha256": "034753ef8a7c7ee8b9b4f6ab04e8bd0314851f96079754fb1bda99620adf090f",
          "sha1": "a76a928e51c4df1ca0889e76b1b5612b9028ab4d",
          "md5": "acbcc8389f99831c745e1da792c4d6db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-types-1.0.0-javadoc.jar",
          "url": "rsmod-types-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "04c00bc65ad79fa45a228066ddcb92d1621a9512f2e08357f57ffeb8cadfef7c0d74784bc0a296cffa2df373119aff550db01697d2c1d3324efec771d3564fab",
          "sha256": "319995d04664aae989234fec5cd904de31172335dcf0d05cfede9fc5aa23ba36",
          "sha1": "63d33bf8ae9c7d9d62223aef1e1e38383ddd0c08",
          "md5": "7659c8070247e96ecda5b27bdf2efdc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-types-1.0.0-sources.jar",
          "url": "rsmod-types-1.0.0-sources.jar",
          "size": 5289,
          "sha512": "0bb9cf5c53b9e1ff4cde31e6641e0f0b9435e1da3925cd33cbc35cb3926c541f1745da14c9fce59dfcfc466b00711311026b2c7bcd17f55b4e3f932225b0c447",
          "sha256": "9b7bb5ccb056d0e0a39d6fdbf6235a390d3ad71dbb1405367683006962790f39",
          "sha1": "becf45630131c9a3aa2b8a4e19626dad8ca535c2",
          "md5": "3c39172e2a1fce2b3d183f3608fb470f"
        },
        {
          "name": "rsmod-types-1.0.0-sources.jar",
          "url": "rsmod-types-1.0.0-sources.jar",
          "size": 5289,
          "sha512": "0bb9cf5c53b9e1ff4cde31e6641e0f0b9435e1da3925cd33cbc35cb3926c541f1745da14c9fce59dfcfc466b00711311026b2c7bcd17f55b4e3f932225b0c447",
          "sha256": "9b7bb5ccb056d0e0a39d6fdbf6235a390d3ad71dbb1405367683006962790f39",
          "sha1": "becf45630131c9a3aa2b8a4e19626dad8ca535c2",
          "md5": "3c39172e2a1fce2b3d183f3608fb470f"
        }
      ]
    }
  ]
}
