{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-scripts",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-scripts-1.0.0.jar",
          "url": "rsmod-scripts-1.0.0.jar",
          "size": 21596,
          "sha512": "e5e0da779acc0499be647b9e186b03e52937a6eab7a51549dcee7423639356edf492d5ba83e70cd186b8bcc4f6884cd81065df81a4c43518885fd3e7ff64e63e",
          "sha256": "b58349ce9459bac62505700157b6467a39ebaae7544f9252367328a4e78f4cb5",
          "sha1": "15fadb154f48fc3c2dc83b86b2ac7b6ef6265592",
          "md5": "d6e0299634ca72b7f454aacd339621e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.158"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-scripts-1.0.0.jar",
          "url": "rsmod-scripts-1.0.0.jar",
          "size": 21596,
          "sha512": "e5e0da779acc0499be647b9e186b03e52937a6eab7a51549dcee7423639356edf492d5ba83e70cd186b8bcc4f6884cd81065df81a4c43518885fd3e7ff64e63e",
          "sha256": "b58349ce9459bac62505700157b6467a39ebaae7544f9252367328a4e78f4cb5",
          "sha1": "15fadb154f48fc3c2dc83b86b2ac7b6ef6265592",
          "md5": "d6e0299634ca72b7f454aacd339621e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-scripts-1.0.0-javadoc.jar",
          "url": "rsmod-scripts-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "568e3298a5637b6a25c389b872827ddbcb7a64704ee23508b283d44ad33c2878b9ba1dfedb36343c64c6a89a757b00c5cdfd163464b03b01a6ded823192fe78b",
          "sha256": "47134fdb511fe41875f31c14818b9ba2c3fef3f8418667532a231d17bd5758e7",
          "sha1": "85c880ef3dd8bfa13c79671908d756bbf5b156e3",
          "md5": "cb365671f496b23fea2dfc6d32185204"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-scripts-1.0.0-sources.jar",
          "url": "rsmod-scripts-1.0.0-sources.jar",
          "size": 6398,
          "sha512": "24f31acdf4f561df105c4652cdba018152c8cae10896cb56b554212197d88a92f485f439fd6382304b59f4111e9c65b525c4ac6ccd785aec5cba643ef123ba91",
          "sha256": "64d4b2964351cee3bca2c0268ad4812866b057046155c5763c1d14342fb02d39",
          "sha1": "933823db5d9cdf948561bc9dd37b71c80ff965d9",
          "md5": "1542a3cc8cca91c3809a471fb806dbe3"
        },
        {
          "name": "rsmod-scripts-1.0.0-sources.jar",
          "url": "rsmod-scripts-1.0.0-sources.jar",
          "size": 6398,
          "sha512": "24f31acdf4f561df105c4652cdba018152c8cae10896cb56b554212197d88a92f485f439fd6382304b59f4111e9c65b525c4ac6ccd785aec5cba643ef123ba91",
          "sha256": "64d4b2964351cee3bca2c0268ad4812866b057046155c5763c1d14342fb02d39",
          "sha1": "933823db5d9cdf948561bc9dd37b71c80ff965d9",
          "md5": "1542a3cc8cca91c3809a471fb806dbe3"
        }
      ]
    }
  ]
}
