{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "js5server-displee",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-displee-1.0.0.jar",
          "url": "js5server-displee-1.0.0.jar",
          "size": 6342,
          "sha512": "978e8a37d87cf51f0fe930aa78c357c6ac5f4a8f334d42c19fb312c745a230336a309b925fc95b46ccbcdfb65892f2f19e26b48d5ad1614b4ac1802eba9425e1",
          "sha256": "726cf403b6e21429915bb6a75ada162fa887af8c0d31a322a85a936f4c57b8ad",
          "sha1": "20b35e30553a0ea6de2776be48731898f1751a8f",
          "md5": "1b05caca2bf1fcf503d438896f1cdaaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.advo",
          "module": "js5server",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-displee-1.0.0.jar",
          "url": "js5server-displee-1.0.0.jar",
          "size": 6342,
          "sha512": "978e8a37d87cf51f0fe930aa78c357c6ac5f4a8f334d42c19fb312c745a230336a309b925fc95b46ccbcdfb65892f2f19e26b48d5ad1614b4ac1802eba9425e1",
          "sha256": "726cf403b6e21429915bb6a75ada162fa887af8c0d31a322a85a936f4c57b8ad",
          "sha1": "20b35e30553a0ea6de2776be48731898f1751a8f",
          "md5": "1b05caca2bf1fcf503d438896f1cdaaa"
        }
      ]
    }
  ]
}
