{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "cachetool",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cachetool-1.0.0.jar",
          "url": "cachetool-1.0.0.jar",
          "size": 13329,
          "sha512": "52ae6f0be78aff7f33ec0461f63743e0f36baede3327e60cf950668dc40286a3149c5095701b309718b867897f3039bafa011b9c66f618da0f7a8378a15dd75a",
          "sha256": "dca7c9edbebd421511b5d16f5ace7fe197b5603223f9ec311d50bc4262862db4",
          "sha1": "81b70353378c63d28ddb4aa4b1ed3f20a77048ed",
          "md5": "7cd73ec7d1a779ad4427d23ee4d37829"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.itadaki",
          "module": "bzip2",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "cachetool-1.0.0.jar",
          "url": "cachetool-1.0.0.jar",
          "size": 13329,
          "sha512": "52ae6f0be78aff7f33ec0461f63743e0f36baede3327e60cf950668dc40286a3149c5095701b309718b867897f3039bafa011b9c66f618da0f7a8378a15dd75a",
          "sha256": "dca7c9edbebd421511b5d16f5ace7fe197b5603223f9ec311d50bc4262862db4",
          "sha1": "81b70353378c63d28ddb4aa4b1ed3f20a77048ed",
          "md5": "7cd73ec7d1a779ad4427d23ee4d37829"
        }
      ]
    }
  ]
}
