{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.advo",
    "module": "rsmod-json",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-json-1.0.0.jar",
          "url": "rsmod-json-1.0.0.jar",
          "size": 3581,
          "sha512": "1c6da4cbf3d382f637f8b6924cb2e96fb3e9f3ec9d72a49195edf2c9faae90d2a373360f62bc202c502d87f50324055819b3c267087088efa27118650682e0fc",
          "sha256": "4c0f3468f327d47b85367be89740e4f5fa4989f3be37da5513adbe59bcae4d9d",
          "sha1": "c40b9e040c901e7a2e737d1b44919b11230408a9",
          "md5": "55de150e7e1b53f7989a86c61147d566"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-json-1.0.0.jar",
          "url": "rsmod-json-1.0.0.jar",
          "size": 3581,
          "sha512": "1c6da4cbf3d382f637f8b6924cb2e96fb3e9f3ec9d72a49195edf2c9faae90d2a373360f62bc202c502d87f50324055819b3c267087088efa27118650682e0fc",
          "sha256": "4c0f3468f327d47b85367be89740e4f5fa4989f3be37da5513adbe59bcae4d9d",
          "sha1": "c40b9e040c901e7a2e737d1b44919b11230408a9",
          "md5": "55de150e7e1b53f7989a86c61147d566"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-json-1.0.0-javadoc.jar",
          "url": "rsmod-json-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "cbf29587f9dd641bcb1778a01f7d9ec248b1e5fc0bbc03f2bf09552d7e549f61319395a7dc7ae0c39a3e7201a59b33f2f882d53643585ac27684160cd69502d4",
          "sha256": "3877756a5047a6cce3b39dfc03272c56b399782d71b51ac899fd521b4dc530c4",
          "sha1": "e958affc04c0e260eb472c96560f7f47570b7fb9",
          "md5": "30aa8af0585ad019f32ee3c4d9679f36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsmod-json-1.0.0-sources.jar",
          "url": "rsmod-json-1.0.0-sources.jar",
          "size": 1702,
          "sha512": "ea5bb03f3290778446648a400754262f99b5666b09635e5600510c5f38e9724f0d337ebec2992c783ea3e457f9765fdd3967f9ba1883c66fa4c980a907b52525",
          "sha256": "59728b70e0e0ad3245c734cf9d7f17b47988eb6527b6a08b77ded3e0eb1bb08d",
          "sha1": "6656a75153c3d29a7eb36386928875b79acd6b86",
          "md5": "e24f039e796e3b59c4ffc48fd203428a"
        },
        {
          "name": "rsmod-json-1.0.0-sources.jar",
          "url": "rsmod-json-1.0.0-sources.jar",
          "size": 1702,
          "sha512": "ea5bb03f3290778446648a400754262f99b5666b09635e5600510c5f38e9724f0d337ebec2992c783ea3e457f9765fdd3967f9ba1883c66fa4c980a907b52525",
          "sha256": "59728b70e0e0ad3245c734cf9d7f17b47988eb6527b6a08b77ded3e0eb1bb08d",
          "sha1": "6656a75153c3d29a7eb36386928875b79acd6b86",
          "md5": "e24f039e796e3b59c4ffc48fd203428a"
        }
      ]
    }
  ]
}
