{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rsprot",
    "module": "crypto",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-1.0-SNAPSHOT.jar",
          "url": "crypto-1.0-SNAPSHOT.jar",
          "size": 10138,
          "sha512": "a4042255d2ca8add80cd11cbc18b25b4edbaa2c306ecd8f0b913aa64289ba449eea945bce6f19da81b1d290d841b2ac43047b1964d105a392e6a427defa110c1",
          "sha256": "a9683e0ace515e3edcafe071469d8c5926da8c48ca42688ffdeef2de40729b12",
          "sha1": "2be542f95311fc95bff939693f990f45e76db586",
          "md5": "a9fed2829ebd4454ed857cbf088fb393"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-bom",
          "version": {
            "requires": "4.1.107.Final"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-1.0-SNAPSHOT.jar",
          "url": "crypto-1.0-SNAPSHOT.jar",
          "size": 10138,
          "sha512": "a4042255d2ca8add80cd11cbc18b25b4edbaa2c306ecd8f0b913aa64289ba449eea945bce6f19da81b1d290d841b2ac43047b1964d105a392e6a427defa110c1",
          "sha256": "a9683e0ace515e3edcafe071469d8c5926da8c48ca42688ffdeef2de40729b12",
          "sha1": "2be542f95311fc95bff939693f990f45e76db586",
          "md5": "a9fed2829ebd4454ed857cbf088fb393"
        }
      ]
    }
  ]
}
