{
  "formatVersion": "1.1",
  "component": {
    "group": "net.rsprot",
    "module": "protocol",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "protocol-1.0-SNAPSHOT.jar",
          "url": "protocol-1.0-SNAPSHOT.jar",
          "size": 45469,
          "sha512": "826d82dfb31f0d997b833db990ed90f54184e191597176068e62fb37ca11d66abb66b745add9a97c3d5c145e93e2476cb66dd4ebd7b163f2cac66529260750b8",
          "sha256": "bc31451cb96c21789fbba71f50c516d9d234fbad05a23953368fce11157cb53c",
          "sha1": "1fa46c68130bc2eacc72d75b94a9055c8729c4a5",
          "md5": "7e93aedf4638a847c53e62c31ce49539"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-bom",
          "version": {
            "requires": "4.1.109.Final"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "io.netty",
          "module": "netty-transport"
        },
        {
          "group": "net.rsprot",
          "module": "buffer",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "crypto",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.rsprot",
          "module": "compression",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "protocol-1.0-SNAPSHOT.jar",
          "url": "protocol-1.0-SNAPSHOT.jar",
          "size": 45469,
          "sha512": "826d82dfb31f0d997b833db990ed90f54184e191597176068e62fb37ca11d66abb66b745add9a97c3d5c145e93e2476cb66dd4ebd7b163f2cac66529260750b8",
          "sha256": "bc31451cb96c21789fbba71f50c516d9d234fbad05a23953368fce11157cb53c",
          "sha1": "1fa46c68130bc2eacc72d75b94a9055c8729c4a5",
          "md5": "7e93aedf4638a847c53e62c31ce49539"
        }
      ]
    }
  ]
}
